export const USER = {
  CURRENT: 'USER_CURRENT',
  INFO: 'USER_INFO',
  ROLES: 'USER_ROLES',
  PERMISSION: 'USER_PERMISSION',
  URL_LOGIN_SUCCESS: 'layout/timemanagement/presencemanagement',
  MENU: 'USER_MENU',
  MENU_MODULE: 'MODULE',
  VIEW: {
    LOGIN: 'USER_VIEW_LOGIN',
    LOGOUT: 'USER_VIEW_LOGOUT',
    EMAIL: 'USER_VIEW_EMAIL',
    EMAIL_PLACEHOLDER: 'USER_VIEW_EMAIL_PLACEHOLDER',
    FORGOT_PASSWORD: 'USER_VIEW_FORGOT_PASSWORD',
    CHANGE_PASSWORD: 'USER_VIEW_CHANGE_PASSWORD',
    PASSWORD: 'USER_VIEW_PASSWORD',
    PASSWORD_PLACEHOLDER: 'USER_VIEW_PASSWORD_PLACEHOLDER',
    NEW_PASSWORD: 'USER_VIEW_NEW_PASSWORD',
    NEW_PASSWORD_PLACEHOLDER: 'USER_VIEW_NEW_PASSWORD_PLACEHOLDER',
    RE_NEW_PASSWORD: 'USER_VIEW_RE_NEW_PASSWORD',
    RE_NEW_PASSWORD_PLACEHOLDER: 'USER_VIEW_RE_NEW_PASSWORD_PLACEHOLDER',
    CONFIRM: 'USER_VIEW_CONFIRM',
    SAVE: 'USER_VIEW_SAVE',
    OTP_TITLE: 'USER_VIEW_OTP_TITLE',
    OTP_TITLE_DESCRIPTION: 'USER_VIEW_OTP_TITLE_DESCRIPTION',
    OTP_PLACEHOLDER: 'USER_VIEW_OTP_PLACEHOLDER',
    OTP_QUESTION: 'USER_VIEW_OTP_QUESTION',
    OTP_RESEND: 'USER_VIEW_OTP_RESEND',
    OTP_RESEND_ZERO: 'USER_VIEW_OTP_RESEND_ZERO',
    MY_ACCOUNT: {
      TITLE: 'USER_VIEW_MY_ACCOUNT_TITLE'
    }
  },
  OTP: {
    TYPE: 'USER_OTP_TYPE',
    EMAIL: 'USER_OTP_EMAIL',
    PASSWORD: 'USER_OTP_PASSWORD',
    FORGOT_PASSWORD: 'USER_OTP_FORGOT_PASSWORD'
  }
}

export const ROLES = {
    LIST: 'ROLES_LIST',
    HRA_LEADER: 'HRA_LEADER',
    CB: 'CB',
    BOD: 'BOD',
    EMPLOYEE: 'EMPLOYEE',
    PO: 'PO',
    PRM: 'PRM',
    TEAM_LEADER: 'TEAM_LEADER',
}

export const ROLE_LIST = {
    CRUM_MASTER: 'CRUM_MASTER',
    PRODUCT_OWNER: 'PRODUCT_OWNER',
    DEVOPS: 'DEVOPS',
    BUSINESS_ANALYST: 'BUSINESS_ANALYST',
    DEVELOPER: 'DEVELOPER',
    QUALITY_CONTROL: 'QUALITY_CONTROL',
    TEAM_LEADER: 'TEAM_LEADER',
    // BOD
    CEO: 'CEO',
    COO: 'COO',
    CFO: 'CFO',
    CMO: 'CMO',
    CTO: 'CTO',
    // BOD
    DESIGNER: 'DESIGNER',
    MARKETING_EXECUTIVE: 'MARKETING_EXECUTIVE',
    MARKETING_LEADER: 'MARKETING_LEADER',
    SALES: 'SALES',
    SALES_ADMIN: 'SALES_ADMIN',
    SALES_LEADER: 'SALES_LEADER',
    C_B: 'C_B',
    RECRUITER: 'RECRUITER',
    ADMIN: 'ADMIN',
    L_D: 'L_D',
    HRA_LEADER: 'HRA_LEADER',
    OPERATIONS_EXECUTIVE: 'OPERATIONS_EXECUTIVE',
    PROJECT_MANAGER: 'PROJECT_MANAGER',
    PRM_LEADER: 'PRM_LEADER',
    QUALITY_ASSURANCE: 'QUALITY_ASSURANCE',
    CASHIER: 'CASHIER',
    FINANCE_ACCOUNTING_LEADER: 'FINANCE_ACCOUNTING_LEADER',
}

export const TRANSLATE = {
  KEY: 'exception-message',
  EXISTS: 'TRANSLATE_EXISTS'
}

export const LANGUAGE = {
  KEY: 'LANGUAGE_KEY',
  VALUE: 'LANGUAGE_VALUE',
  VI: 'VI',
  VI_VALUE: 'Tiếng Việt',
  EN: 'EN',
  LIST: 'LANGUAGE_LIST'
}

export const HOME = {
  DASHBOARD: {
    TITLE_NAME: 'HOME_DASHBOARD_TITLE_NAME'
  }
}

export const HEADERS = {
  AUTHORIZATION: 'Authorization',
  ACCEPT_LANGUAGE: 'Accept-Language',
  CLIENT_KEY: 'Client_key',
  CLIENT_SECRET: 'Client_secret',
  CONTENT_TYPE: 'Content-Type',
};

export const CANDIDATE = {
  LIST: {
    TITLE_NAME: 'CANDIDATE_LIST_NAME',
    CREATE_DATE_FROM: 'CANDIDATE_LIST_CREATE_DATE_FROM',
    CREATE_DATE_TO: 'CANDIDATE_LIST_CREATE_DATE_TO',
    SEARCH: 'CANDIDATE_LIST_SEARCH',
    ASSIGN_HR: 'CANDIDATE_LIST_ASSIGN_HR',
    UPLOAD_CV: 'CANDIDATE_LIST_UPLOAD_CV',
    EXPORT: 'CANDIDATE_LIST_EXPORT',
    IMPORT: 'CANDIDATE_LIST_IMPORT',
    ADD_NEW: 'CANDIDATE_LIST_ADD_NEW',
  },
  VIEW: {
    BOX: {
      CANDIDATE_INFO: 'CANDIDATE_VIEW_BOX_CANDIDATE_INFO',
      CONTRACT_CHANNEL_ADD: 'CANDIDATE_VIEW_BOX_CONTRACT_CHANNEL_ADD'
    }
  },
  MODEL: {
    CANDIDATE_CODE: 'CANDIDATE_MODEL_CANDIDATE_CODE',
    CANDIDATE_CODE_PLACEHOLDER: 'CANDIDATE_MODEL_CANDIDATE_CODE_PLACEHOLDER',
    FULL_NAME: 'CANDIDATE_MODEL_FULL_NAME',
    FULL_NAME_PLACEHOLDER: 'CANDIDATE_MODEL_FULL_NAME_PLACEHOLDER',
    BIRTH_DATE: 'CANDIDATE_MODEL_BIRTH_DATE',
    BIRTH_DATE_PLACEHOLDER: 'CANDIDATE_MODEL_BIRTH_DATE_PLACEHOLDER',
    GENDER: 'CANDIDATE_MODEL_GENDER',
    GENDER_PLACEHOLDER: 'CANDIDATE_MODEL_GENDER_PLACEHOLDER',
    EMAIL: 'CANDIDATE_MODEL_EMAIL',
    EMAIL_PLACEHOLDER: 'CANDIDATE_MODEL_EMAIL_PLACEHOLDER',
    CREATE_DATE: 'CANDIDATE_MODEL_CREATE_DATE',
    CREATE_DATE_PLACEHOLDER: 'CANDIDATE_MODEL_CREATE_DATE_PLACEHOLDER',
    ONBOARD_DATE: 'CANDIDATE_MODEL_ONBOARD_DATE',
    ONBOARD_DATE_PLACEHOLDER: 'CANDIDATE_MODEL_ONBOARD_DATE_PLACEHOLDER',
    APPLY_POSITION: 'CANDIDATE_MODEL_APPLY_POSITION',
    APPLY_POSITION_PLACEHOLDER: 'CANDIDATE_MODEL_APPLY_POSITION_PLACEHOLDER',
    TECHNOLOGY: 'CANDIDATE_MODEL_TECHNOLOGY',
    TECHNOLOGY_PLACEHOLDER: 'CANDIDATE_MODEL_TECHNOLOGY_PLACEHOLDER',
    STATUS: 'CANDIDATE_MODEL_STATUS',
    STATUS_PLACEHOLDER: 'CANDIDATE_MODEL_STATUS_PLACEHOLDER',
    PHONE: 'CANDIDATE_MODEL_PHONE',
    PHONE_PLACEHOLDER: 'CANDIDATE_MODEL_PHONE_PLACEHOLDER',
    HR: 'CANDIDATE_MODEL_HR',
    HR_PLACEHOLDER: 'CANDIDATE_MODEL_HR_PLACEHOLDER',
    ADDRESS: 'CANDIDATE_MODEL_ADDRESS',
    ADDRESS_PLACEHOLDER: 'CANDIDATE_MODEL_ADDRESS_PLACEHOLDER',
    SOURCE: 'CANDIDATE_MODEL_SOURCE',
    SOURCE_PLACEHOLDER: 'CANDIDATE_MODEL_SOURCE_PLACEHOLDER',
    RECEIVE_TIME: 'CANDIDATE_MODEL_RECEIVE_TIME',
    RECEIVE_TIME_PLACEHOLDER: 'CANDIDATE_MODEL_RECEIVE_TIME_PLACEHOLDER',
    JD_LINK: 'CANDIDATE_MODEL_JD_LINK',
    JD_LINK_PLACEHOLDER: 'CANDIDATE_MODEL_JD_LINK_PLACEHOLDER',
    CONTACT_CHANNEL: 'CANDIDATE_MODEL_CONTACT_CHANNEL',
    CONTACT_CHANNEL_PLACEHOLDER: 'CANDIDATE_MODEL_CONTACT_CHANNEL_PLACEHOLDER',
    CONTACT_INFO: 'CANDIDATE_MODEL_CONTACT_INFO',
    CONTACT_INFO_PLACEHOLDER: 'CANDIDATE_MODEL_CONTACT_INFO_PLACEHOLDER',
    FILE_CV: 'CANDIDATE_MODEL_FILE_CV',
    FILE_CV_PLACEHOLDER: 'CANDIDATE_MODEL_FILE_CV_PLACEHOLDER',
    FILE_CV_COMMENT: 'CANDIDATE_MODEL_FILE_CV_COMMENT',
    ROLES: 'CANDIDATE_MODEL_ROLES',
  }
}

export const COMMON = {
  PAGINATION: {
    DISPLAY_RECORD: 'COMMON_PAGINATION_DISPLAY_RECORD',
    DISPLAY_OF: 'COMMON_PAGINATION_DISPLAY_OF',
    RECORD: 'COMMON_PAGINATION_RECORD',
    NO: 'COMMON_PAGINATION_NO',
    NOT_EXIST: 'COMMON_PAGINATION_NOT_EXIST'
  },
  VALIDATE: {
    REQUIRED: 'COMMON_VALIDATE_REQUIRED',
    PATTERN: 'COMMON_VALIDATE_PATTERN',
    MAX_LENGTH: 'COMMON_VALIDATE_MAX_LENGTH',
    MIN_LENGTH: 'COMMON_VALIDATE_MIN_LENGTH',
    EQUALS_PASSWORD: 'COMMON_VALIDATE_EQUALS_PASSWORD'
  },
  NOTIFY: {
    TITLE: 'COMMON_NOTIFY_TITLE'
  },
  WARNING: {
    TITLE: 'COMMON_WARNING_TITLE'
  }
}

export const OPTION_PAGE_SIZE = [
  {value: 10},
  {value: 20},
  {value: 30},
  {value: 50},
  {value: 100}
];

export const TENANTS = {
  PERU: 'PE',
  MOZ: 'MZ',
  LAO: 'LA'
}

export const LANGUAGES = {
  VI: 'vi'
  , EN: 'en'
  , ES : 'es'
}

export const ERROR_STATUS = {
  ACCESS_TOKEN: {
    EXPIRED: 'ACCESS_TOKEN_EXPIRED'
  }
}

export const CHARACTERS = {
  DOT: '.',
  COMMA: ',',
  SPACE: ' ',
};


export const CURRENCY_MASK = {
  CURRENT_CONFIG: {
    round: 0,
    pattern: 'separator.0',
    thousandSeparator: CHARACTERS.COMMA,
  },
  MOZ_CONFIG: {
    round: 0,
    pattern: 'separator.0'
  },
  PERU_CONFIG: {
    round: 2,
    pattern: 'separator.2'
  },
  LAO_CONFIG: {
    round: 2,
    pattern: 'separator.2',
    thousandSeparator: CHARACTERS.COMMA,
  },
  EN_SEPARATOR: CHARACTERS.COMMA,
  VI_SEPARATOR: CHARACTERS.DOT,
  ES_SEPARATOR: CHARACTERS.COMMA,
};

export const PLATFORM = {
  isWeb: true
  , isAndroid: false
  , isIos: false
  , isTablet: false
  , isIpad: false
  , isPortrait: false
};